var books=[
    {'id':0,
     'title':'Harry Potter',
     'subbtitle':'The Goblet of Fire',
     'price':590,
     'author':'JK Rowling',
     'edition':2008,
     'genre':'thriller,sci-fi,action',
     'desc':'this is so and so.',
     'photo':'harrypotter.jpg'
    },
    {'id':1,
     'title':'2 States',
     'subbtitle':'',
     'price':300,
     'author':'Chetan Bhagat',
     'edition':2011,
     'genre':'Romantic, Drama',
     'desc':'this is so and so.',
     'photo':'2states.jpg'
    },
    {'id':2,
     'title':'Physics Class 12',
     'subbtitle':'',
     'price':210,
     'author':'Anonymous',
     'edition':2010,
     'genre':'',
     'desc':'this is so and so.',
     'photo':'phy12part1.jpg'
    },
    {'id':3,
     'title':'Computer Science with Python',
     'subbtitle':'',
     'price':190,
     'author':'Sumita Arora',
     'edition':2015,
     'genre':'',
     'desc':'this is so and so.',
     'photo':'cswp12.jpg'
    },
    {'id':4,
     'title':'Harry Potter',
     'subbtitle':'The Goblet of Fire',
     'price':590,
     'author':'JK Rowling',
     'edition':2008,
     'genre':'thriller,sci-fi,action',
     'desc':'this is so and so.',
     'photo':'harrypotter.jpg'
    },
    {'id':5,
     'title':'2 States',
     'subbtitle':'',
     'price':300,
     'author':'Chetan Bhagat',
     'edition':2011,
     'genre':'Romantic, Drama',
     'desc':'this is so and so.',
     'photo':'2states.jpg'
    },
    {'id':6,
     'title':'Physics Class 12',
     'subbtitle':'',
     'price':210,
     'author':'Anonymous',
     'edition':2010,
     'genre':'',
     'desc':'this is so and so.',
     'photo':'phy12part1.jpg'
    },
    {'id':7,
     'title':'Computer Science with Python',
     'subbtitle':'',
     'price':190,
     'author':'Sumita Arora',
     'edition':2015,
     'genre':'',
     'desc':'this is so and so.',
     'photo':'cswp12.jpg'
    },
    {'id':8,
     'title':'Harry Potter',
     'subbtitle':'The Goblet of Fire',
     'price':590,
     'author':'JK Rowling',
     'edition':2008,
     'genre':'thriller,sci-fi,action',
     'desc':'this is so and so.',
     'photo':'harrypotter.jpg'
    },
    {'id':9,
     'title':'2 States',
     'subbtitle':'',
     'price':300,
     'author':'Chetan Bhagat',
     'edition':2011,
     'genre':'Romantic, Drama',
     'desc':'this is so and so.',
     'photo':'2states.jpg'
    },
    {'id':10,
     'title':'Physics Class 12',
     'subbtitle':'',
     'price':210,
     'author':'Anonymous',
     'edition':2010,
     'genre':'',
     'desc':'this is so and so.',
     'photo':'phy12part1.jpg'
    },
    {'id':11,
     'title':'Computer Science with Python',
     'subbtitle':'',
     'price':190,
     'author':'Sumita Arora',
     'edition':2015,
     'genre':'',
     'desc':'this is so and so.',
     'photo':'cswp12.jpg'
    },
    {'id':12,
     'title':'Harry Potter',
     'subbtitle':'The Goblet of Fire',
     'price':590,
     'author':'JK Rowling',
     'edition':2008,
     'genre':'thriller,sci-fi,action',
     'desc':'this is so and so.',
     'photo':'harrypotter.jpg'
    },
    {'id':13,
     'title':'2 States',
     'subbtitle':'',
     'price':300,
     'author':'Chetan Bhagat',
     'edition':2011,
     'genre':'Romantic, Drama',
     'desc':'this is so and so.',
     'photo':'2states.jpg'
    }];

    export default books;